# Generated by Django 3.2.9 on 2021-11-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre Grupo/Cantante')),
                ('debutYear', models.DateField(verbose_name='Año de debut')),
                ('biography', models.TextField(verbose_name='Biografia')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Titulo')),
                ('album', models.CharField(max_length=50, verbose_name='Album')),
                ('release_date', models.DateField(verbose_name='Fecha de lanzamiento')),
                ('views', models.IntegerField(verbose_name='Visitas')),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.artist')),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
    ]
