# Generated by Django 3.2.9 on 2021-11-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20211114_2033'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={},
        ),
    ]
