# Generated by Django 3.2.9 on 2021-11-14 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_songs_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='songs',
            options={'verbose_name': 'Song', 'verbose_name_plural': 'Songs'},
        ),
    ]
