# Generated by Django 3.2.9 on 2021-11-14 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20211114_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='audio',
            field=models.FileField(null=True, upload_to='Songs/'),
        ),
        migrations.AddField(
            model_name='songs',
            name='collab_artists',
            field=models.ManyToManyField(related_name='Collab', to='catalog.Artist'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Artist', to='catalog.artist'),
        ),
    ]
