# Generated by Django 3.2.9 on 2021-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20211114_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='collab_artists',
            field=models.ManyToManyField(null=True, related_name='Collab', to='catalog.Artist'),
        ),
    ]
