# Generated by Django 3.2.9 on 2021-11-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_songs_collab_artists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Album'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Artist'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Songs/'),
        ),
        migrations.AlterField(
            model_name='songs',
            name='collab_artists',
            field=models.ManyToManyField(blank=True, related_name='Collab', to='catalog.Artist'),
        ),
    ]
