# Generated by Django 3.2.9 on 2021-11-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20211114_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Visitas'),
        ),
    ]
