# Generated by Django 3.2.9 on 2021-11-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20211122_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Visitas'),
        ),
    ]
