# Generated by Django 3.2.9 on 2021-11-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_songs_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='imageB',
            field=models.ImageField(blank=True, null=True, upload_to='images/Artist/Banner'),
        ),
    ]
