# Generated by Django 3.2.9 on 2021-11-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20211124_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Album', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Artist', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='imageB',
            field=models.ImageField(blank=True, null=True, upload_to='images/Artist/Banner', verbose_name='Imagen Banner'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Countries', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Genre', verbose_name='Imagen'),
        ),
    ]
